
<div class="col-md-8">
    <p>
<!--    <div class="page-header"><h3>Sobre el autor</h3></div>

    Hola!, soy PGC, vivo en Concepción, tengo 27 años de edad y soy desarrollador de software de profesión. Me interesa los tcg y videojuegos de estrategia en general, llevo años jugando Magic y recien estoy conociendo Vanguard.<br><br>
   <!-- Uno de mis defectos es, supongo, el individualismo, y otro, el perfeccionismo. Me gusta hacer las cosas en persona, hacerlas a mi manera, y la única forma que tengo de controlar que sean hechas a mi manera es haciéndolas yo mismo. No por ello me considero una persona egoísta, soy agradecido cuando corresponde, ni tampoco una persona perfecta, cometo muchos errores que espero me reporten. Sin, embargo me gusta poder decir que esta site, sea grande o pequeña, es de mi autoría, que es mía. Quizá si encontrara una persona que contara con mi más plena confianza, tuviera más o menos mis mismos criterios y conocimientos tecnicos me plantearía pedirle su ayuda, pero hasta ahora poca gente se aproxima a ello.<br><br> -->

   <!-- <div class="page-header"><h3>¿Por que hago la web?</h3></div>
    La razón se divide en dos partes. La primera es que cuando me inicie note que era dificil encontrar información(decks especificamente) de Vanguard a diferencia de otros tcg que cuentan con webs especializados de mazos, con estadísticas, porcentajes, rankings, etc(como lo pretende ser esta web), solo había a disposición unos pocos blog que tocaban el tema que no terminaban por satisfacerme. El segundo motivo es que me gusta la programación, en mis tiempos libres suelo documentarme para aprender lenguajes o tecnicas nuevas y programar herramientas que en su mayoría solo quedan para mí o en el olvido. Con esta web puedo programar y al mismo tiempo desarrollar herramientas que puedan ser util para los demas.  <br><br>  -->
    <div class="page-header"><h3>Sobre el sitio</h3></div>
    Vgdecks es una página de origen chileno que nace con el objetivo de ser una base de datos de decks para Cardfight Vanguard. El sitio esta hecho para que cualquier usuario pueda enviar sus decks o torneos al sitio para posteriomente mostrarse instantaneamente.<br><br>
<!-- Como se puede observar, trato de centrar el contenido de la website en el tcg únicamente. La razón es sencilla, esos otros campos no me atraen casi en absoluto, y sin el interés necesario es imposible que llegue a saber demasiado de temas como anime, manga o merchandising. Esta web es también una afición, por ello no trato cuestiones de las que no voy a disfrutar. Pese a todo, en mi afán de serles de utilidad, procuraré proporcionarles algunos otros sitios web que informen de esos temas, o, si algún día, quién sabe, encuentro a alguien de confianza interesado en alguno de esos temas, quizá lo termine tratando. De cualquier manera, es el tcg los que realmente son el motor de Vanguard, y a los que mayor atención se les debe prestar. <br><br> -->

    El sitio esta escrito bajo lenguaje PHP, Zend Framework 2, Bootstrap y Jquery, . La información de las cartas y los decks se almacenan en una base de datos Mysql 
    </p>
</div>    


