<?php
$form   =   $this->form;
$form->prepare();
$form->setAttributes(array(
    'action' => '',
    'method' => 'post'   
));
$formLabel  =   $this->plugin('formLabel');
echo $this->form()->openTag($form);
?>
<div class="page-header">
    <h1><?=$this->translate($this->titulo)?></h1>
</div>
<div class="row">
    <div class="col-md-3"><?=$this->translate('Nombre del torneo')?><?=$this->formElement($form->get('name'))?></div>        
    <div class="col-md-3"><?=$this->translate('Cantidad de jugadores')?><?=$this->formElement($form->get('num_players'))?></div>
    <div class="col-md-3"><?=$this->translate('Fecha')?><?=$this->formElement($form->get('date'))?></div>
    <div class="col-md-3" align="center"><br><?=$this->formElement($form->get('modificar_torneo'))?></div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="table-responsive">
            <table style="background:transparent;" class="table table-striped table-hover table-condensed">
                <thead>
                    <tr>
                        <th>Deck id</th>
                        <th><?=$this->translate('Deck')?></th>
                        <th><?=$this->translate('Jugador')?></th>
                        <th><?=$this->translate('Arquetipo')?></th>
                        <th><?=$this->translate('Posición')?></th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <?php foreach($this->decks as $var){?>
                <tr>
                    <td><?=$var['deck_id']?></td>
                    <td><a href="<?=$this->basePath()?>/modulos/decks/ver/<?=$var['deck_id']?>"><?=$var['deck_name']?></a></td>
                    <td><?=$var['deck_player']?></td>
                    <td><a href="<?=$this->basePath()?>/modulos/decks/verarquetipo/<?=$var['id_clan']?>"><?=$var['deck_archetype']?></a></td>
                    <td><?=$var['deck_place']?></td>
                    <td><a class="btn btn-default btn-sm" type="button" href="<?=$this->basePath()?>/modulos/admin/modificardeck/<?=$var['deck_id']?>"><?=$this->translate('Modificar')?></a></td>
                    <td><a class="btn btn-default btn-sm" type="button" href="<?=$this->basePath()?>/modulos/admin/deletedeck/<?=$var['deck_id']?>/<?=$this->id?>"><?=$this->translate('Eliminar')?></a></td>
                </tr>
                <?php }?>
            </table>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag();?>