<?php
$form   =   $this->form;
$form->prepare();
$form->setAttributes(array(
    'action' => '',
    'method' => 'post',
));
$formLabel  =   $this->plugin('formLabel');
echo $this->form()->openTag($form);
?>
<div class="page-header"><h1><?=$this->translate($this->titulo)?></h1></div>
<div class="row">
    <div class="col-md-3">
        Card Id<div class="form-group"><?=$this->formElement($form->get('cardid'))?></div>
    </div>
    <div class="col-md-3">
        Name<div class="form-group"><?=$this->formElement($form->get('name'))?></div>
    </div>
    <div class="col-md-3">
        Power<div class="form-group"><?=$this->formElement($form->get('power'))?></div>
    </div>
    <div class="col-md-3">
        Shield<div class="form-group"><?=$this->formElement($form->get('shield'))?></div>
    </div>
</div>
<div class="row">
    <div class="col-md-3">
        Trigger<div class="form-group"><?=$this->formElement($form->get('triggers'))?></div>
    </div>
    <div class="col-md-3">
        Clan<div class="form-group"><?=$this->formElement($form->get('archetype'))?></div>
    </div>
    <div class="col-md-3">
        Uclass<div class="form-group"><?=$this->formElement($form->get('uclass'))?></div>
    </div>
    <div class="col-md-3">
        Grade/Skill<div class="form-group"><?=$this->formElement($form->get('skillicon'))?></div>
    </div>
</div>
<div class="row">
    <div align="center">
        <?=$this->formElement($form->get('buscar'))?>
    </div>
</div>
<br>
<div class="table-responsive">
    <table style="background:transparent;" class="table table-hover table-striped table-condensed">
        <thead>
            <tr>
                <th>Card Id</th>
                <th>Name</th>
                <th>Trigger</th>
                <th>Grade/Skill</th>
                <th>Power</th>
                <th>Shield</th>
                <th>Clan</th>
            </tr>
        </thead>
        <?php foreach($this->cards as $var){?>
        <tr>
            <td><?=$var['cardID']?></td>
            <?php $img = $var['name'];?>
            <td><a href="<?=$this->basePath()?>/modulos/cartas/detalle?id=<?=$var['cardID']?>" rel="popover" data-img="<?=$this->basePath()?>/public/img/cards/<?=$img?>.png"><?=$var['name']?></a></td>
            <td><?php if($var['triger'] == ''){ echo "-";}else{ echo $var['triger'];}?></td>
            <td><?=$var['grade_skill']?></td>
            <td><?=$var['power']?></td>
            <td><?php if($var['shield'] == ''){ echo "-";}else{ echo $var['shield'];}?></td>
            <td><?=$var['clan']?></td>
        </tr>
        <?php } ?>
    </table>
</div>
<?=$this->paginationControl($this->cards,'Sliding','numpaginacion',array('route' =>$this->route,'action'=>$this->action));?>
<?php echo $this->form()->closeTag();?>
<script>
    $('a[rel=popover]').popover({
        html: true,
        trigger: 'hover',
        placement: 'right',
        content: function(){return '<img style="border-radius:20px;" width="90%" src="'+$(this).data('img') + '" />';}

    });
</script>