<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/public/img/favicon.ico'))
    ->prependStylesheet($this->basePath('public/css/style.css'))
    ->prependStylesheet($this->basePath('public/css/footer-distributed.css'))
    //->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
    ->prependStylesheet($this->basePath('public/css/bootstrap.min.css')) ?>

        <!-- <link href="<?php echo $this->basePath()?>/css/style.css">
<link href="<?php echo $this->basePath()?>/css/bootstrap-theme.min.css" rel="stylesheet">
<link href="<?php echo $this->basePath()?>/css/bootstrap.min.css" rel="stylesheet"> --!>

<!-- Scripts -->
        <?php echo $this->headScript()
    ->prependFile($this->basePath('public/js/bootstrap.min.js'))
    ->prependFile($this->basePath('public/js/jquery.min.js'))
    ->prependFile($this->basePath('public/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->basePath('public/js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

    </head>
    <body style="background: transparent;">
        <?php echo $this->content; ?>
    </body>
</html>
