<div class="page-header"><h1><?=$this->datos['name']?></h1></div>
<?php
    $flash=$this->flashMessenger()
    ->setMessageOpenFormat('<div%s>')
    ->setMessageSeparatorString('')
    ->setMessageCloseString('</div>');
echo $flash->render('msg',array('alert', 'alert-dismissible alert-warning'));
?>
<div class="row">
    <div class="col-md-8">
        <div class="table-responsive">
            <table style="background:transparent;" class="table table-striped table-hover table-condensed">
                <thead>
                    <tr>
                        <th><?=$this->translate('Deck')?></th>
                        <th><?=$this->translate('Jugador')?></th>
                        <th><?=$this->translate('Arquetipo')?></th>
                        <th><?=$this->translate('Posición')?></th>
                    </tr>
                </thead>
                <?php foreach($this->decks as $var){?>
                <tr>
                    <td><a href="<?=$this->basePath()?>/modulos/decks/ver/<?=$var['deck_id']?>"><?=$var['deck_name']?></a></td>
                    <td><?=$var['deck_player']?></td>
                    <td><a href="<?=$this->basePath()?>/modulos/decks/verarquetipo/<?=$var['id_clan']?>"><?=$var['deck_archetype']?></a></td>
                    <td><?=$var['deck_place']?></td>
                </tr>
                <?php }?>
            </table>
        </div>
        <div align="center"><a href="<?=$this->basePath()?>/modulos/torneos/agregardeck/<?=$this->id?>" class="btn btn-default">Agregar otro deck</a></div>
    </div>
    <div class="col-md-4">
        <div class="well">
            <table style="background:transparent;">
                <tr>
                    <th><?=$this->translate('Nombre del torneo')?></th>
                    <th>&nbsp;:&nbsp;</th>
                    <td><?=$this->datos['name']?></td>
                </tr>
                <tr>
                    <th><?=$this->translate('Cantidad de jugadores')?></th>
                    <th>&nbsp;:&nbsp;</th>
                    <th><?=$this->datos['num_players']?></th>
                </tr>
                <tr>
                    <th><?=$this->translate('Fecha')?></th>
                    <th>&nbsp;:&nbsp;</th>
                    <th><?=$this->datos['date']?></th>
                </tr>
            </table>
        </div>
        <div class="page-header">
            <h3><?=$this->translate('Estadística de arquetipos')?></h3>
        </div>
        <canvas id="canvas"></canvas>
         <div class="page-header">
            <h3><?=$this->translate('Compartir')?></h3>
        </div>
        <div class="fb-like"></div>
        <script src="https://apis.google.com/js/platform.js" async defer></script>
        <br>
        <g:plusone></g:plusone>
         <a href="https://twitter.com/share" class="twitter-share-button" data-via="P4blo_GC">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
    </div>
</div>
<script type="text/javascript" src="<?=$this->basePath()?>/public/js/Chart.js"></script>
<script>
    var datos=<?=json_encode($this->clans);?>;
    var labels = new Array();
    var data = new Array();
    for(x=0; x<datos.length;x++){
        labels[x] = datos[x]['name_clan'];
        data[x] = datos[x]['cantidad'];
    }   
    var RadarChart = {
        labels: labels,
        datasets: [{
            fillColor: "rgba(151,187,205,0.2)",
            strokeColor: "rgba(151,187,205,1)",
            pointColor: "rgba(151,187,205,1)",
            pointStrokeColor: "#fff",
            pointHighlightFill: "#fff",
            pointHighlightStroke: "rgba(151,187,205,1)",
            data: data
        }]
    }

    var myRadarChart = new 
    Chart(document.getElementById("canvas").getContext("2d")).Radar(RadarChart, {pointLabelFontSize : 13, pointLabelFontColor  : "#ffa45e"});
</script>
<div id="fb-root"></div>
<div id="fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v2.5&appId=1582540375324289";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>  